logging:
    enabled: true
    level: info
    file: .steiner/steiner.log

model: gemma4

models:
    qwopus:
        type: openai_compat
        base_url: http://localhost:1234/v1
        model: qwen3.5-9b-glm5.1-distill-v1
        context_size: 131072
        max_completion_tokens: 8192
        compaction:
            safety_margin_tokens: 30720
            summary_max_tokens: 7168

    qwen36:
        type: openai_compat
        base_url: http://localhost:1234/v1
        model: qwen3.6-35b-a3b
        context_size: 32768
        max_completion_tokens: 4096
        compaction:
            safety_margin_tokens: 4096
            summary_max_tokens: 4096

    gemma4:
        type: openai_compat
        base_url: http://localhost:1234/v1
        model: gemma-4-26b-a4b-it@iq4_nl
        context_size: 16400
        max_completion_tokens: 4096
        compaction:
            safety_margin_tokens: 4096
            summary_max_tokens: 4096
        # context_size: 32768
        # max_completion_tokens: 4096
        # compaction:
        #     safety_margin_tokens: 4096
        #     summary_max_tokens: 4096

    openrouter_free:
        type: openai_compat
        base_url: https://openrouter.ai/api/v1/
        model: openrouter/free
        api_key: ${OPENROUTER_API_KEY}
        context_size: 16400
        max_completion_tokens: 4096
        compaction:
            safety_margin_tokens: 4096
            summary_max_tokens: 4096
approval:
    # default: prompt
    default: prompt
    overrides:
        # bash: prompt
        bash: auto
        glob: auto
        read: auto
        search: auto
        # write: prompt
        write: auto
